### ISSUE TITLE
TypeError: generate() got an unexpected keyword argument 'resolve'

### ISSUE THREAD

**Issue by struffel** [elisiariocouto/jsonschema-markdown#8]
I ran into a problem while trying to run the CLI version of this program.
I installed it via pip in an empty `python:3.11` docker container (this felt easier for testing that using the provided image).
However, when trying to start using the command `jsonschema-markdown /wd/json-schema/template/meta.json` (with /wd being the directory I have mounted into the container) I kept getting this stacktrace:

```
root@9ba04be8da37:/# jsonschema-markdown --version
jsonschema-markdown, version 0.3.1
root@9ba04be8da37:/# jsonschema-markdown /wd/json-schema/template/meta.json
Traceback (most recent call last):
  File "/usr/local/bin/jsonschema-markdown", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jsonschema_markdown/main.py", line 63, in cli
    markdown = jsonschema_markdown.generate(file_contents, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate() got an unexpected keyword argument 'resolve'
```
Below is the content of the schema file meta.json:
```
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"response_id": {
		  "type": "string"
		},
		"version": {
		  "type":"string"
		},
		"kind": {
		  "type": "string"
		},
		"message": {
		  "type": "string"
		}
	},
	"required": ["kind","version"]
}
```

**Comment by elisiariocouto** [comment]
Hello @struffel, there was a bug on the keyword argument for an experimental feature involving JSON Refs.
I was able to reproduce the issue. Fixed in version 0.3.2.

Thank you for your report!
